### ISSUE TITLE
At the moment the angular-counter do not supports multiple coutners on page.

### ISSUE THREAD

**Issue by lukaskalcok** [indrimuska/angular-counter#4] opened 2016-06-10 14:09 UTC
At the moment the angular-counter do not supports multiple coutners on page.
I've created updated version that supports multiple counters. Would you like me to add pull request?

**Comment by indrimuska** [comment] 2016-06-10 14:15
Hi @izy-izzy, it sounds a little strange to me to hear these words.
Angular Counter supports multiple counters on page as you can see in the plunker example in the README file:
http://plnkr.co/edit/d1KPDa?p=preview
Is there something I am missing?

**Comment by lukaskalcok** [comment] 2016-06-10 17:01
Yeah, Super weird. 

It was not like it would not work. It just changed the value of the first one and then counting values on the second counter.

I had to do this to meke it work ... :

html:

```
<counter identificator="counter-2" value="vmChartCtrl.counters.views.value" to="vmChartCtrl.counters.views.target" duration="vmChartCtrl.counters.views.duration" effect="'easeOutExpo'"> 
    {{ vmChartCtrl.counters.views.value | number:0 }} 
</counter>
<br/><br/>
<counter identificator="counter-1" value="vmChartCtrl.counters.searches.value" to="vmChartCtrl.counters.searches.target" duration="vmChartCtrl.counters.searches.duration" effect="'easeOutExpo'"> 
    {{ vmChartCtrl.counters.searches.value | number:0 }} 
</counter><br/><br/>
```

js/controller:

```
this.counters = {
                searches: {
                    value: 0,
                    target: 0,
                    duration: 1500
                },
                views: {
                    value: 0,
                    target: 0,
                    duration: 1500
                }
            };
```

I've updated the service in angular-counter as this:

```
CounterService.prototype.count = function (identificator, from, to, duration, effect, step, finish) {
            // stop previous animation
            this.counter[identificator] = { value : 0 };
            $(this.counter[identificator]).stop(true, true);
            this.counter[identificator].value = parseFloat(from || 0);

            if (this.counter[identificator].value == parseFloat(to || 0)) return;

            $(this.counter[identificator]).animate({ value: parseFloat(to || 0) }, {
                duration: duration,
                easing: effect,
                step: step
            }).promise().done(function () {
                if (angular.isFunction(finish)) finish();
            });
        };

...


function CounterDirective(counter, timeout) {
            this.restrict = 'EAC';
            this.scope = {
                identificator : '=',
                to:       '=',
                value:    '=',
                effect:   '=?',
                duration: '=?',
                finish:   '&?'
            };
            $counter = counter;
            $timeout = timeout;
        };


...

$scope.$watch('to', function () {
                $counter.count($scope.identificator, $scope.value, $scope.to, $scope.duration, $scope.effect, $scope.step, $scope.finish);
            });
```

And now it works.

**Comment by indrimuska** [comment] 2016-06-11 10:10
Wait, wait, wait!
Angular Counters **supports** multiple counters on the same page.

I don't know why you said that it changes just the first counter, maybe it could be a browser lack.
Have you noticed that in the example the other counters can be fired manually by clicking on the "Start now!" label?

Please, give a check to this second plunker: http://plnkr.co/edit/hcIMCNecKnNl3be90ylE?p=preview
**Note** that counters starts only after clicking the buttons in the "Controls" section.
Waiting for your feedback. :)

**Comment by lukaskalcok** [comment] 2016-06-11 17:33
Hi,

I've tried both the plnkr-s And tried to achive the result as it is in my project but unsucessfull ... It may by caused by some other dependancy that I'm using at the moment. There is like 50 of them. I would say dismiss this bug, I will have my branch with different version and use the one on my github.

I thik the problem in my project is that For you It creates multiple services. One for each of the counters. When I tried it in my project only one service is created and obviously ... then the counters are interfearing. ... very strange ...

**Comment by indrimuska** [comment] 2016-06-13 10:13
Ok, I'm going to go ahead and close this issue. Feel free to to re-open it again if you still have any problems.

**Closed as completed by indrimuska** 2016-06-13 10:13 UTC
Labels: help wanted

**Comment by stiekel** [comment] 2016-06-29 03:29
I got the same error, and after I change the code that provided by @izy-izzy, multiple counter works.

**Comment by indrimuska** [comment] 2016-06-29 06:41
Well, two people having the same issue it's absolutely not a coincidence.
Ok @stiekel, are you able to provide a valide example showing this issue? I was thinking that it can be due to an integration problem with some other directive..

**Comment by stiekel** [comment] 2016-06-29 07:09
I copy the html and js array form my porject to plnkr, But both counters works currently ^_*
http://plnkr.co/edit/8hjwd9cZRYAgsYwXZN7D?p=preview

Angular 1.5.0 / jQuery 3.0.0 / jQuery Easing 1.3.2

**Comment by indrimuska** [comment] 2016-06-29 08:03
So, you're saying that your app works in Plunker but not in your Project?

**Comment by stiekel** [comment] 2016-06-29 08:45
yes, you are right.

you can ignore this issue, If I got more about this, I will write it down here.

**Comment by indrimuska** [comment] 2016-06-29 08:47
Sounds very very strange. Are you sure you're testing exactly the same files? Does your app work locally?

**Comment by stiekel** [comment] 2016-06-29 10:02
In my project, I got the code from izy-izzy, you can check it [here](https://github.com/izy-izzy/angular-counter/commit/feb09853fbc4403709247ca1e51e9792eb9b1482).

**Comment by indrimuska** [comment] 2016-06-30 18:19
To be honest, I don't like the solution with an extra `identificator` attribute, because I think that the user does not have to be of interest to the id of the counters, it should be totally transparent to the user and prevented inside the directive.

However, if there's an issue then I'd like to fix it.
The real problem for me now is that I don't have an example or a something similar to test to build an universal solution. Please, let me know if someone of you can create and provide me a working app that shows this behavior.
Thanks.

**Comment by stiekel** [comment] 2016-06-30 22:15
thanks for you passion.

**Comment by Nargonath** [comment] 2016-11-16 16:12
I'm having a similar problem when using the directive inside a `ng-repeat` loop. I loop over an array of this form :

``` javascript
[
  {
    "num": 32290,
    "start": 0
  },
  {
    "num": 402,
    "start": 0
  },
  {
    "num": 71,
    "start": 0
  },
  {
    "num": 20,
    "start": 0
  }
]
```

The property `start` is the `value` passed to the directive and `num` matches the `to` property. 
The result is that only the last element in the array is being increased up to the `num` value. The rest get set straight up to the target value.

The result I wanted to achieve is having 4 counters running at the same time on the page.

I wonder if the problem is not due to the fact that a service is instantiated only once in an application by the service factory thus all 4 counters share the same information.

**Comment by lukaskalcok** [comment] 2016-11-16 16:28
You can try my fork if it works. Let me know.

**Comment by Nargonath** [comment] 2016-11-16 16:29
@izy-izzy That was my plan but I was leaving a comment in case we can update this module. Btw I updated my previous answer.

> I wonder if the problem is not due to the fact that a service is instantiated only once in an application by the service factory thus all 4 counters share the same information.

**Comment by Nargonath** [comment] 2016-11-16 16:56
@izy-izzy Your solution works but the funny thing is that is still work with multiple counters even though I do not pass the `identificator` attribute to the `counter` directive. Perhaps there is a way to add your fix into the plugin without using the `identificator` attribute which would please @indrimuska.
Thanks for the fix anyway.

**Comment by lukaskalcok** [comment] 2016-11-17 08:34
Ok now it`s getting even more interesting :) I would have to look into the code again to see what has been changed except the identificator so it works.

**Comment by lukaskalcok** [comment] 2016-11-17 09:16
It's weird. The directive has an isolated scope so this should not happen. 

I'm starting to think that the culprit here is the usage of the **target** thing. Even though it is strange because it is created as a new object in each function call.

Anyway @Nargonath can you provide html of your counters?

**Comment by Nargonath** [comment] 2016-11-17 17:51
Alright here the HTML for my counters :

``` html
<div class="stat" ng-repeat="stat in $ctrl.counters">
      <div class="stat-content">
        <div class="counter" to="stat.num" duration="1500" value="stat.start">
          {{ stat.start }}
        </div>
      </div>
    </div>
```

Here the structure of the `$ctrl.counters` :

``` json
[
  {
    "num": 32290,
    "start": 0
  },
  {
    "num": 402,
    "start": 0
  },
  {
    "num": 71,
    "start": 0
  },
  {
    "num": 20,
    "start": 0
  }
]
```
